# Toda configuração desse arquivo corresponde ao sistema, são estas:
# atualização do sistema operacional e configuração do Hostname
---
- name: Atualizando os pacotes apt
  apt: update_cache=yes force_apt_get=yes
  
- name: Configurando o hostname para padrão correto
  ansible.builtin.hostname:
    name: p01-Julio-Ryan
