# Toda a configuração desse arquivo corresponde ao NFS
# Além do arquivo de monitoramento

---
# CONFIGURAÇÃO DO NFS





# CONFIGURAÇÃO DO ARQUIVO DE MONITORAMENTO
- name: Transmitindo o arquivo de monitoramento
  copy: 
    src: ~/Vagrant_Ansible/playbooks/tasks/conf_NFS/monitoramento.sh
    dest: /usr/local/bin/monitoramento.sh
    owner: root
    group: root
    mode: '0755'

- name: Garantindo que o arquivo sempre será ativado para todos os usuários
  lineinfile:
    path: /etc/profile
    line: "usr/local/bin/monitoramento.sh"
    create: yes
    state: present
