# Toda a configuração desse playbook está de acordo aos usuários
# Aqui possui a configuração criação de usuários, mensagem de saudação, SUDO e SSH

---
# CRIANDO OS USUÁRIOS
- name: Criando o 1° user
  user:
    name: julio
    shell: /bin/bash
    home: /home/julio

- name: Criando o 2° user
  user:
    name: ryan
    shell: /bin/bash
    home: /home/ryan


      
# CRIAÇÃO DO GRUPO IFPB
- name: Criando o grupo ifpb e aplicando o SUDO
  ansible.builtin.group:
    name: ifpb
    state: present

# APLICANDO O SUDO NO GRUPO IFPB
- name: Colocando SUDO no grupo IFPB      
  copy:
    dest: /etc/sudoers.d/{{ sudo_group }}
    content: "{{ sudo_group }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  vars:
    sudo_group: ifpb



      
# CRIAÇÃO DA MENSAGEM DE SAUDAÇÃO
- name: Adicionando uma messagem de SSH para todos os usuários
  lineinfile:
    path: /etc/profile
    line: |
      echo "Acesso restrito apenas à pessoas com autorização expressa"
      echo "Seu acesso está sendo monitorado !!!"
    insertafter: EOF
