# Toda a configuração desse playbook está de acordo aos usuários
# Aqui possui a configuração criação de usuários, grupos, e SUDO 

---
# CRIANDO OS USUÁRIOS
- name: Criando o 1° user
  user:
    name: julio
    password: "$6$8a83clfyST1D9jPb$CuxsTYjGxbSmXBikFdFzLEcBLgVfRjVTfcOf8KMNlEfTdW6DhGq4lG67dilpoq2EBwedWcoiT512RVDpXi7O4."
    shell: /bin/bash
    home: /home/julio

- name: Criando o 2° user
  user:
    name: ryan
    password: "$6$Y2HS5gc5WvcLkccS$EXOUqZ6qF9/743QqXRVnzytX9nYXHn.3NsnGM/9fqIr1Wnf5M8bNcNoIyJ13PNho/CLvUXc/.NacncLUqgEjc1"
    shell: /bin/bash
    home: /home/ryan

#---------------------------------------------------------------------------------------------------      

# CRIAÇÃO DO GRUPO IFPB
- name: Criando o grupo ifpb e aplicando o SUDO
  ansible.builtin.group:
    name: ifpb
    state: present

# CRIAÇÃO DO GRUPO ACESSO_SSH
- name: Criando o grupo acesso_ssh
  ansible.builtin.group:
    name: acesso_ssh
    state: present

# ADICIONANDO OS USUÁRIOS AO GRUPO ACESSO_SSH
- name: Adição dos usuário ryan ao grupo acesso_ssh
  ansible.builtin.user:
    name: ryan
    groups: acesso_ssh
    append: yes
- name: Adição do usuário julio ao grupo acesso_ssh
  ansible.builtin.user:
    name: julio
    groups: acesso_ssh
    append: yes

# APLICANDO O SUDO NO GRUPO IFPB
- name: Colocando SUDO no grupo IFPB      
  copy:
    dest: /etc/sudoers.d/{{ sudo_group }}
    content: "{{ sudo_group }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'
  vars:
    sudo_group: ifpb

#---------------------------------------------------------------------------------------------------
