###      Main Playbook    ###
#============================#

# (pt-BR) Este playbook executa as roles definidas no escopo do projeto,
#         garantindo a configuração do ambiente e a aplicação das tasks necessárias.

# (en-US) This playbook executes the roles defined in the project scope,
#         ensuring environment setup and the execution of required tasks.

- hosts: servers
  become: true
  become_user: root
  roles:
    - common/conf_Sys
    - common/conf_users
    - common/conf_SSH
    - common/conf_LVM
    - common/conf_NFS