- name: Execução dos playbooks por um playbook principal
  hosts: servidores
  become: true
  become_user: root
  tasks:
    - name: Inclusão do Playbook de conf do sistema
      include_tasks: ./tasks/conf_Sys/main.yaml

    - name: Inclusão do Playbook de conf dos usuários
      include_tasks: ./tasks/conf_users/main.yaml

    - name: Inclusão do Playbook de conf do SSH
      include_tasks: ./tasks/conf_SSH/main.yaml

    - name: Inclusão do Playbook de conf do volumes
      include_tasks: ./tasks/conf_LVM/main.yaml

    - name: Inclusão do Playbook de conf do NFS
      include_tasks: ./tasks/conf_NFS/main.yaml