# Esse playbook será executado dentro do processo "vagrant up"
# e vai chamar todos os outros playbooks

---
- name: Execução dos playbooks por um playbook principal
  hosts: servidores
  become: true
  become_user: root
  tasks:
    - name: Inclusão do Playbook de conf do sistema
      include_tasks: ~/Vagrant_Ansible/playbooks/tasks/conf_Sys/conf_sistema.yaml

    - name: Inclusão do Playbook de conf dos usuários
      include_tasks: ~/Vagrant_Ansible/playbooks/tasks/conf_users/conf_usuarios.yaml

    - name: Inclusão do Playbook de conf do SSH
      include_tasks: ~/Vagrant_Ansible/playbooks/tasks/conf_SSH/conf_ssh.yaml

    - name: Inclusão do Playbook de conf do LVM
      include_tasks: ~/Vagrant_Ansible/playbooks/tasks/conf_LVM/conf_lvm.yaml

    - name: Inclusão do Playbook de conf do NFS
      include_tasks: ~/Vagrant_Ansible/playbooks/tasks/conf_NFS/conf_nfs.yaml
